name: shell-checks
on:
  push:
  pull_request:
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: bash -n warp-masque.sh
      - name: Verify os-release can be loaded without variable collisions
        run: bash -c 'source ./warp-masque.sh; source /etc/os-release; test -n "$APP_VERSION"; test -n "$ID"'
      - run: sudo apt-get update && sudo apt-get install -y shellcheck
      - run: shellcheck warp-masque.sh
